---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Covariance Estimation for Random Surfaces beyond Separability

<!-- badges: start -->
<!-- badges: end -->

The purpose of this repo is to allow for reproducibility of the simulation studies and applications in papers

* Random Surface Covariance Estimation by Shifted Partial Tracing
[[arXiv:1912.12870v2]](https://arxiv.org/abs/1912.12870) (a.k.a. separable-plus-banded model),
* Principal Separable Component Analysis via the Partial Inner Product
[[arXiv:2007.12175v1]](https://arxiv.org/abs/2007.12175) (a.k.a. separable component decomposition),
* Inference and Computation for Sparsely Sampled Random Surfaces
[[arXiv:2103.10077v1]](https://arxiv.org/abs/2103.10077) (a.k.a. sparsely observed separable model),

which constitute the doctoral thesis of the author.

While the separable-plus-banded model and the separable component decomposition form the basis for the
`surfcov` package available [here](https://github.com/TMasak/surfcov), the package was created only later.
The simulation studies in the paper are instead produced by the scripts included here, which contain
all the functions. As such, this
repo provides the code for reproducing the results in the aforementioned papers. A total majority of
these were computed on a [cluster](https://www.epfl.ch/research/facilities/scitas/). The remainder of this
page shows examples how to reproduce (chunks of) the results on a single machine, running
R version 4.0.4 (2021-02-15).

There may be errors in the code (especially in parts not explicitly covered below). If a mistake is
found, please contact the author at tomas[tecka]masak[zavinac]epfl[tecka]ch.

## Separable-plus-banded Model

In the respective folder, [library.R](separable_plus_banded_model/library.R) contains functions implementing
all the algorithms from the [paper](https://arxiv.org/abs/1912.12870).

Script [demo](separable_plus_banded_model/demo.R) shows how the functions can be used in form of a sample
simulation run.

### Simulation Study

Most of the results in Section 5.1 of the [paper](https://arxiv.org/abs/1912.12870)
corresponding to the scripts in the [separate folder](separable_plus_banded_model/scripts) were computed on a cluster. 
The resulting data are stored in the [data folder](separable_plus_banded_model/data).

To reproduce, for example, the data underlying the left panel of Figure 2 on a single machine, open
[script_legendre_ar_buf.R](separable_plus_banded_model/scripts/script_legendre_ar_buf.R), comment out the
following two lines at the bottom of the script

``` r
library(parallel)
data <- mclapply(1:25,simulate,mc.cores=25)
```

and uncomment

``` r
# data <- lapply(1:25,simulate)
```

The script can then be run to reproduce
[legendre_ar_buf.RData](separable_plus_banded_model/data/legendre_ar_buf.RData).

The resulting data are in turn used by [results.R](separable_plus_banded_model/results.R) to create
the left panel of Figure 2, apart from the bias curve. All the bias curves are computed separately (and locally)
using [script_norms.R](separable_plus_banded_model/script_norms.R)

A similar workflow can be followed to re-create any Figure in the paper. Check in
[results.R](separable_plus_banded_model/results.R) which data files are needed for the plot.
The scripts producing the data have similar names to the data files themselves.

TODO: We have apparently used the triangular kernel instead of the Epanechnikov kernel in the respective simulations.
Of course, this does not affect the results very much (differences should not be visible by eye), but the next version of the paper should mention the triangular kernel instead of Epanechnikov.

### Mortality Data Analysis

The raw data were downloaded from the [Human Mortality Database](https://www.mortality.org/) on 12/4/209/
The .txt files were saved in a folder, labeled "death_rates". Then, the script [mortality_data_read.R](separable_plus_banded_model/mortality_data_read.R) was used to produce
`mortality_data.RData`.
As requested by the Human Mortality Database, we do not distribute the data set, hence users have to
go through this process themselves.

After `mortality_data.RData` is created, [mortality_analysis.R](separable_plus_banded_model/mortality_analysis.R)
can be used to reproduce the graphical outputs of Section 5.2 of the paper. The empirical bootstrap tests
are conducted in a separate script: [testing.R](separable_plus_banded_model/testing.R).

## Separable Component Decomposition

In the respective folder, [library_PIP.R](separable_component_decomposition/library_PIP.R) contains 
functions implementing all the algorithms from the [paper](https://arxiv.org/abs/2007.12175).

Script [demo](separable_plus_banded_model/demo.R) shows how the functions can be used in form of a sample
simulation run.

### Simulation Study

All the resulting data with the exception of runtimes
([script_fourier_runtimes.R](separable_component_decomposition/script_fourier_times.R))
were run on a cluster.

To reproduce the data, follow the workflow above.

To re-create the plots in the paper, use [plots.R](separable_component_decomposition/plots.R).

## Sparsely Observed Random Surfaces

Unlike the previous methodologies, this is not a part of the `surfcov` package.
This is because while the previous two parts were
completely self-contained, utilizing only packages in the base R distribution, the codes
in this section require some additional packages such as
[np](https://cran.r-project.org/web/packages/fdapace/index.html)
and [fdapace](https://cran.r-project.org/web/packages/np/index.html),
and some modifications of their functions.

In the respective folder [library_kronPCA.R](sparsely_observed_random_surfaces/library_kronPCA.R) and
[library_PIP.R](sparsely_observed_random_surfaces/library_smooth.R) contain all the
functions implementing methodologies from the paper.

Script [demo](sparsely_observed_random_surfaces/demo.R) shows how the functions can be used in form of a sample
simulation run.

### Simulation Study

Different scripts generate data of the same name appended with "_data". Those scripts were
run on a cluster. To reproduce the data, run the scripts using the workflow described above.

All simulation-based figures in the paper and in the supplement can be recreated from the data
in this folder using [results.R](sparsely_observed_random_surfaces/results.R)

### Implied Volatility Surfaces





